### ISSUE TITLE
chat.privacytools.io / Riot tracking issue

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/services#17]
## chat.privacytools.io/selfhosted instance issues

*Check boxes as they are fixed on PTIO*

* [ ] Host Dimension instead of relying on vector.im
    * upstream issue letting clients know about it: https://github.com/vector-im/riot-web/issues/6430
        * [x] upstream spec and sdk change allowing this has been merged https://github.com/matrix-org/matrix-doc/pull/1957 & https://github.com/matrix-org/matrix-react-sdk/pull/3340
* [ ] Host identity server ***OR*** set it to chat.privacytools.io (same as homeserver) so it won't work.
    * https://github.com/matrix-org/matrix-doc/blob/6e8739c989172c351a6ead66f073b413f6340326/api/client-server/login.yaml#L147-L148 ?
    * Update 10/7: I don't know if our fix actually works currently so I'm unchecking this box, see: https://github.com/privacytoolsIO/privacytools.io/issues/1049#issuecomment-539269846
* [ ] Host Jitsi Meet
    * upstream: ~~https://github.com/vector-im/riot-web/issues/7711 ***`WONTFIX`***~~ https://github.com/vector-im/riot-web/issues/6930

## Upstream privacy issues

* **[Upstream Privacy Tracker](https://vector-im.github.io/feature-dashboard/#/plan?label=privacy-sprint&repo=vector-im/riot-web&repo=vector-im/riot-ios&repo=vector-im/riot-android&repo=vector-im/riotX-android&repo=matrix-org/matrix-doc&repo=matrix-org/sydent)** which seems to have different priorities and miss some issues below, notably Tor and actually removing removed messages from the database.

### major

Privacy issues that I think prevent PTIO listing:

* matrix-org/matrix-doc#447 - history is stored forever, there is no way to limit how much or how long
    * Signal & Wire: messages aren't stored on server, clients have option how many old messages to keep + both also support disappearing/timed/exploding messages.
* matrix-org/synapse#1263 - uploaded media/files aren't removed when they are removed in Riot
* ~~matrix-org/synapse#1287 - actually removing removed messages from the database~~ fixed
* https://github.com/vector-im/riot-web/issues/7649 / https://github.com/matrix-org/matrix-doc/pull/2134 - private contact discovery
    *I am not sure which topic to put this under, but Signal & Wire both have this.*
* https://github.com/matrix-org/matrix.org/issues/342 - Matrix.org uses Cloudflare (issue closed without disabling Cloudflare)
    * See also https://github.com/privacytoolsIO/privacytools.io/issues/374. I understand this to mean that Cloudflare can one way or another read all traffic going through Matrix.org including IRC users who have never even heard of Matrix if someone happens to use Matrix on the same IRC channel? Matrix.org is quite big compared to an individual Cloudflaring their IRC client, I have heard a number 1500 connections associated with a I-line request from third party bridge admin.
    * Wire and Signal [citation needed] apparently have support pages behind Cloudflare https://github.com/wireapp/wire-webapp/issues/5716.

#### major privacy issues also with selfhosting

I consider these as major due to Cloudflare as the traffic to integration manager and identity server would go through it and so would all messages assuming the user federated with Matrix.org. These may be irrelevant to user who is on Matrix.org.

* https://github.com/vector-im/riot-web/issues/10161 - Store Integration Manager preferences in account data and allow user to change them somewhere sensible
* https://github.com/vector-im/riot-web/issues/10167 - Present an aggregated terms of service dialogue at registration if possible
* https://github.com/vector-im/riot-web/issues/10087 - Prompt to accept integration manager policies on registration
* https://github.com/vector-im/riot-web/issues/10094 - Store identity server in Account Data and support choosing identity server integration in User Settings
* https://github.com/vector-im/riotX-android/issues/20 - Identity server is hardcoded in RiotX (Android client rewrite), the issue is closed and no one has commented on identity server since it was pointed out on 2019-07-09.

### medium

*I need a better word here, but these would be issues that also affect other recommended instant messengers and may not be a blocker.*

* https://github.com/matrix-org/synapse/issues/4565 - metadata resistance
    * to-read for me, is this similar like Wire server knows connections between users, or is this a more serious one?*

### nice to have

* vector-im/riot-web#4426 - riot does not scrub exif data from upload
    * [Discord apparently does](https://github.com/privacytoolsIO/privacytools.io/issues/1049#issuecomment-531200503), [Signal](https://github.com/signalapp/Signal-iOS/pull/2907) and [Wire](https://github.com/wireapp/wire/issues/208) do.
* https://github.com/vector-im/riot-meta/issues/287 - Proxy/Tor support meta issue
    * I cannot find option to enable Tor use either in Signal or Wire, Conversations would have it
    * https://github.com/vector-im/riot-web/issues/3320 - desktop
    * https://github.com/vector-im/riot-android/issues/1234 - Android
    * https://github.com/vector-im/riot-ios/issues/1085 - iOS

### unsorted / note

* matrix-org/synapse#1941 - allow account deletion, not just deactivation
    * I am not sure where exactly to put this either.
* https://github.com/vector-im/riot-web/issues/7757 - Open source the integrations server ***`WONTFIX`***
* https://github.com/vector-im/riot-web/issues/6739 - stickers aren't encrypted
* Less technical users may register on matrix.org unknowingly by default
    * https://github.com/vector-im/riot-ios/issues/2614
    * ~~https://github.com/vector-im/riotX-android/issues/450~~
    * https://github.com/vector-im/riot-android/issues/3238

## Research papers

* [Notes on privacy and data collection of Matrix.org](https://github.com/libremonde-org/paper-research-privacy-matrix.org/blob/master/part1/README.md)
* [Notes on privacy and data collection of Matrix.org, Part 2](https://github.com/libremonde-org/paper-research-privacy-matrix.org/blob/master/part2/README.md)

* * * * *

These issues are mostly took from privacytoolsIO/privacytools.io#840, if you are aware of reported issues that aren't listed here, please do comment them and someone from the team will edit this issue and add them.

I was personally missing a list of things that can be done today to avoid the privacy issues that Matrix/Riot currently has and this may be helpful while considering the delisting (#1047).

**Comment by dm17** [comment]
Are there any current Riot/Element clients (for Linux) that allow for proxies, VPNs, or Tor?
